import time
import os 
print ("I hid it in the attic")
time.sleep(3)
print ("more frantic than the first one.")
time.sleep(2)
print ("For the relief of my sanity, I hid it")
time.sleep(2)
print ("and tucked it in the darkest and dustiest corner")
time.sleep(3)
print ("a white sheet over it as well")
time.sleep(2)
print ("Something inside of me hopes it grows molds")
time.sleep(3)
print ("and maybe")
time.sleep(3)
print ("the worms will eat that instead.")
time.sleep(3)
print("Just")
time.sleep(2)
print ("not me")