import time
import os

print ("Moments after I hid it in my attic")
time.sleep (2)
print ("under a dirty white sheet")
time.sleep (2)
print ("I turned on the TV and news of a car accident that had taken place near the town hall")
time.sleep (3)
print ("at the center of Surcoe")
time.sleep (2)
print ("As the witnesses described it")
time.sleep (2)
os.system('cls')
print ("everything that had transpired was exactly like my painting")
time.sleep (3)
print ("I don't know")
time.sleep (2)
print ("I don't think I can or want to believe any child, lady or man had seen a man melt in front of them")
time.sleep (3)
print ("a melting man reaching out for help of all things")
time.sleep (3)
print ("It was, apparently, a result of drunk driving")
time.sleep (3)
print ("It's happening a lot.")
time.sleep (3)
os.system ('cls')
print ("It's probably not so bad that I never publish any of my work")
time.sleep (2)
print ("lest I get ostracized by the community for my crazy predictions")
time.sleep (3)
print ("I don't think I want to go out this week")
time.sleep (3)
print ("nor use my car anymore.")