import os
import time
print ("I didn't eat again")
time.sleep(3)
print ("Another car accident")
time.sleep(3)
print ("I didn't have a dream.")
time.sleep(3)
print ("I threw out the pork in my freezer.")
time.sleep(3)
print ("It looked like something was moving.")
time.sleep(3)
print ("I didn't want to check again,")
time.sleep(3)
print ("so I threw it in the bin like the rest")
time.sleep(3)
print ("Maybe, the worms are growing there.")
time.sleep(2)
os.system('cls')
print ("I don't have dreams like the last one,")
time.sleep(3)
print ("but I keep painting.")
time.sleep(3)
print ("The last one was the chipped wood in my attic")
time.sleep(3)
print ("and I'm too scared to go in there now")
time.sleep (3)
print ("there's holes in the wood")
time.sleep(3)
os.system('cls')
print ("I felt the urge")
time.sleep(2)
os.system('cls')
print ("I felt the NEED")
time.sleep(3)
print ("TO PAINT IT")
time.sleep(2)
os.system('cls')
print ("I made a friend inside my mirror.")
