import time
import os
print ("I painted something new")
time.sleep(3)
print ("but I feel sick.")
time.sleep(3)
print ("I don't know what it is about dreams")
time.sleep(3)
print ("but it's from our subconscious?")
time.sleep(3)
print ("It's our minds")
time.sleep(3)
print ("our imagination")
time.sleep(3)
print ("it's all mine")
time.sleep(3)
print ("so why did I dream about worms?")
time.sleep(3)
print ("Thick, as the size of your thumbs")
time.sleep(3)
print ("In place of cereal, it was a sick yellow colored worm")
time.sleep(3)
print ("almost like gelatin")
time.sleep(3)
print ("and it was in my bowl")
time.sleep(3)
print ("and why was I eating?")
time.sleep(3)
print ("It was cereal")
time.sleep(3)
print ("I swear.")
time.sleep(3)
os.system('cls')
print ("I woke up, but all I did was paint it")
time.sleep(3)
print("A bowl of worms on a marble counter.")

