import time
import os
print ("The thing about dreams is that most of them are always forgotten, and that should be scary")
time.sleep(5)
print ("I had a dream of a car accident")
time.sleep(3)
print ("a really vivid one")
time.sleep(3)
print ("When I woke up, I felt the urge to paint it")
time.sleep(4)
print ("So, of course, I did.")
time.sleep(5)
os.system('cls')
print ("It's a disfigured man crawling out of his car. His face is melting like goo")
print ("and he's trying to scream but there's nothing coming out- Nothing comes out of a painting, not even him.")
time.sleep(7)
print ("There's a barrier between this painting and reality and he doesn't know it, it's a feeble attempt")
time.sleep(4)
print ("Behind him is a distant image of a red car, flipped upside down and burning")
time.sleep(3)
print ("The side window is broken")
time.sleep (3)
print ("and pieces of glass follow the trail of blood")
time.sleep (3)
print ("from the man in front.")
time.sleep (3)
print ("Behind the car")
time.sleep (3)
print ("is a dead body")
time.sleep (3)
print ("but I didn't see who")
time.sleep (2)
print ("I'd rather not know.")
time.sleep (3)
print ("However, what I do know is that")
time.sleep (2)
print ("this man")
time.sleep (2)
print ("was me")
time.sleep (2)
print ("He could've been me.")