import time 
import os
print ("Moments after I had published it")
time.sleep (2)
print ("unusually")
time.sleep (2)
print ("my phone started ringing in a row")
time.sleep (3)
print ("I left it all on voicemail in favor of a nap")
time.sleep (2)
print ("Thankfully, I didn't have any weird dreams")
time.sleep (3)
print ("not even good ones")
time.sleep (2)
print ("no dreams at all")
time.sleep (2)
print ("but, when I listened to the voicemails, they all")
time.sleep (2)
print ("kept saying the same thing")
time.sleep (3)
print ('''
 ▄  █ ████▄   ▄ ▄       ██▄   ▄█ ██▄       ▀▄    ▄ ████▄   ▄       ██▄   ████▄     ▄█    ▄▄▄▄▀ 
█   █ █   █  █   █      █  █  ██ █  █        █  █  █   █    █      █  █  █   █     ██ ▀▀▀ █    
██▀▀█ █   █ █ ▄   █     █   █ ██ █   █        ▀█   █   █ █   █     █   █ █   █     ██     █    
█   █ ▀████ █  █  █     █  █  ▐█ █  █         █    ▀████ █   █     █  █  ▀████     ▐█    █     
   █         █ █ █      ███▀   ▐ ███▀       ▄▀           █▄ ▄█     ███▀             ▐   ▀      
  ▀           ▀ ▀                                         ▀▀▀                                  
                                                                                               
''')
time.sleep (2)
os.system('cls')
print ("I would be flattered if it was anything about my skills or technique")
time.sleep (3)
print ("not the car accident that happened, at the center of Surcoe, near the town hall")
time.sleep (3)
print ("It was like the painting")
time.sleep (2)
print ("at least")
time.sleep (2)
print ("most of it")
time.sleep (2)
print ("I don't know")
time.sleep (2)
print ("I don't think I can or want to believe any child, lady or man had seen a man melt in front of them")
time.sleep (3)
print ("a melting man reaching out for help of all things")
time.sleep (3)
print ("It was, apparently a result of drunk driving")
time.sleep (3)
print ("It's happening a lot")
time.sleep (2)
os.system('cls')
print ("People know my name when I go out")
time.sleep (2)
print ("I don't think it's for the right reasons.")
time.sleep (2)
print ("Popularity is a hard thing to maintain")
time.sleep (2)
print ("and maybe")
time.sleep (2)
print ("everyone will forget about me if I go out less")
time.sleep (2)
print ("I don't think I want to use my car anymore, either")